Import pandas

In [1]:
import pandas as pd

Opening a local csv file

In [3]:
df =pd.read_csv("Job_Placement_Data.csv")
print(df)

    gender  ssc_percentage ssc_board  hsc_percentage hsc_board hsc_subject  \
0        M           67.00    Others           91.00    Others    Commerce
1        M           79.33   Central           78.33    Others     Science
2        M           65.00   Central           68.00   Central        Arts
3        M           56.00   Central           52.00   Central     Science
4        M           85.80   Central           73.60   Central    Commerce
..     ...             ...       ...             ...       ...         ...
210      M           80.60    Others           82.00    Others    Commerce
211      M           58.00    Others           60.00    Others     Science
212      M           67.00    Others           67.00    Others    Commerce
213      F           74.00    Others           66.00    Others    Commerce
214      M           62.00   Central           58.00    Others     Science

     degree_percentage undergrad_degree work_experience  emp_test_percentage  \
0                58.00         Sci&Tech              No                 55.0
1                77.48         Sci&Tech             Yes                 86.5
2                64.00        Comm&Mgmt              No                 75.0
3                52.00         Sci&Tech              No                 66.0
4                73.30        Comm&Mgmt              No                 96.8
..                 ...              ...             ...                  ...
210              77.60        Comm&Mgmt              No                 91.0
211              72.00         Sci&Tech              No                 74.0
212              73.00        Comm&Mgmt             Yes                 59.0
213              58.00        Comm&Mgmt              No                 70.0
214              53.00        Comm&Mgmt              No                 89.0

    specialisation  mba_percent      status
0           Mkt&HR        58.80      Placed
1          Mkt&Fin        66.28      Placed
2          Mkt&Fin        57.80      Placed
3           Mkt&HR        59.43  Not Placed
4          Mkt&Fin        55.50      Placed
..             ...          ...         ...
210        Mkt&Fin        74.49      Placed
211        Mkt&Fin        53.62      Placed
212        Mkt&Fin        69.72      Placed
213         Mkt&HR        60.23      Placed
214         Mkt&HR        60.22  Not Placed

[215 rows x 13 columns]

In [4]:
df.head()

,gender,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_subject,degree_percentage,undergrad_degree,work_experience,emp_test_percentage,specialisation,mba_percent,status
0,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed
1,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed
2,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed
3,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed
4,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed

Sep Parameters

In [7]:
df=pd.read_csv("Job_Placement_Data.csv",sep="/t")
df

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_18288\3582725800.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df=pd.read_csv("Job_Placement_Data.csv",sep="/t")

    gender,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_subject,degree_percentage,undergrad_degree,work_experience,emp_test_percentage,specialisation,mba_percent,status
0    M,67,Others,91,Others,Commerce,58,Sci&Tech,No,...
1    M,79.33,Central,78.33,Others,Science,77.48,Sci...
2    M,65,Central,68,Central,Arts,64,Comm&Mgmt,No,7...
3    M,56,Central,52,Central,Science,52,Sci&Tech,No...
4    M,85.8,Central,73.6,Central,Commerce,73.3,Comm...
..                                                 ...
210  M,80.6,Others,82,Others,Commerce,77.6,Comm&Mgm...
211  M,58,Others,60,Others,Science,72,Sci&Tech,No,7...
212  M,67,Others,67,Others,Commerce,73,Comm&Mgmt,Ye...
213  F,74,Others,66,Others,Commerce,58,Comm&Mgmt,No...
214  M,62,Central,58,Others,Science,53,Comm&Mgmt,No...

[215 rows x 1 columns]